export const storeProducts =
[
    {id:1,
    title: "chipcookie",
    img: "imgages/chipcookie.png",
    price: 2.25,
    info:"a delicious chocolate chip cookie",
    inCart: false,
    count:0,
    total:0},

    {id:2,
    title: "chocolate chip cookie",
    img: "imgages/cookie2.png",
    price: 1.25,
    info:"a slightly less delicious chocolate chip cookie",
    inCart: false,
    count:0,
    total:0},

    {id:3,
    title: "dino cookie",
    img: "imgages/dinocookie.jpeg",
    price: 2.75,
    info:"a delicious dinosour shaped cookie",
    inCart: false,
    count:0,
    total:0},

    {id:4,
    title: "double chocolate chip",
    img: "imgages/doublechocolate.jpeg",
    price: 2.45,
    info:"a delicious double chocolate chip cookie",
    inCart: false,
    count:0,
    total:0},

    {id:5,
    title: "gingerbread cookie",
    img: "imgages/gingerbread.png",
    price: 4.25,
    info:"a delicious gingerbread  cookie",
    inCart: false,
    count:0,
    total:0},

    {id:6,
    title: "happy cookie",
    img: "imgages/happy.png",
    price: 4.25,
    info:"a happy cookie",
    inCart: false,
    count:0,
    total:0},

    {id:7,
    title: "rasberry fill",
    img: "imgages/rasberryfill.png",
    price: 4.25,
    info:"a delicious rasberry fill cookie",
    inCart: false,
    count:0,
    total:0
},
]
export const detailProduct =

    {id:1,
    title: "chipcookie",
    img: "imgages/chipcookie.png",
    price: 2.25,
    info:"a delicious chocolate chip cookie",
    inCart: false,
    count:0,
    total:0}